# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4b6fefc84744ab0735a4fc6ac4020cae7f9eb53b256c88f7294fe38f58930b6ba37a4717b7623b8a0d1cf2d86b30bd387fd23a5847f5cd380886742b8f4ff73

test:
  secret_key_base: a02f32509a062a61d598bc5dd122fb3bb4d018b90d7a7e923469fe86a44fe512d5800fd4997d31c8b64f779e5539d39b730ce261ce79f0950786956a316ca3e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
